### ISSUE TITLE
blockchain developer role

### ISSUE THREAD

**Issue by hcrypto7** [Pi-Squared-Network/proof-checker-public#14]
Hi, team.
I am a creative and efficient Full stack || blockchain developer with expertise in multiple platforms and programming languages.

My experience includes using Solidity and Rust to create smart contracts on Ethereum, Solana, Polygon, and Binance Smart Chain (BSC). I have developed numerous smart contracts and specialize in gasless, secure, and reliable smart contract development.

In frontend development, I have built decentralized applications (Dapps) using React, Next.js, and Vue. I integrate Web3.js, Ethers.js, and style applications with TailwindCSS, Figma, and Bootstrap. Additionally, I work with wagmi and viem and have proficiency in JavaScript/TypeScript.

On the backend, I utilize Node.js, C#, and Go to develop REST APIs. I incorporate GraphQL and Apollo and connect with databases like Redis, MongoDB, and PostgreSQL. I also have experience with SubGraph for indexing blockchain data.

Apart from coding, I am well-versed in agile methodologies such as Git, Jira, and Kanban for project management. I am eager to join a team where I can further enhance my skills as a blockchain developer and contribute to building the decentralized future.

I am excited about the opportunity to discuss how I can bring value to your team. I look forward to hearing from you soon.

Best regards,
Jack Moes

**Comment by IljaZakharov** [comment]
All instructions on how to apply for a job are outlined on the careers page of our website. Posting your message as an issue is disrespectful and pollutes materials that we would like to have opened to the public. It is behavior that does not align well with our goals and company culture.
